CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    display_name VARCHAR(80),
    avatar_url MEDIUMTEXT,
    role ENUM('USER', 'ADMIN', 'MODERATOR') NOT NULL,
    is_active BIT(1),
    created_at DATETIME(6),
    updated_at DATETIME(6),
    last_login_at DATETIME(6),
    authing_id VARCHAR(100),
    PRIMARY KEY (id),
    UNIQUE KEY uk_users_username (username),
    UNIQUE KEY uk_users_email (email),
    UNIQUE KEY uk_users_phone (phone),
    UNIQUE KEY uk_users_authing_id (authing_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS anime (
    id BIGINT NOT NULL AUTO_INCREMENT,
    mal_id BIGINT,
    title VARCHAR(200) NOT NULL,
    title_japanese VARCHAR(200),
    title_english VARCHAR(200),
    title_cn VARCHAR(200),
    search_aliases VARCHAR(1200),
    synopsis VARCHAR(2000),
    synopsis_cn VARCHAR(2000),
    cover_image VARCHAR(500),
    trailer_url VARCHAR(500),
    type VARCHAR(50),
    status VARCHAR(100),
    aired_from DATE,
    aired_to DATE,
    episodes INT,
    duration_minutes INT,
    rating VARCHAR(50),
    popularity BIGINT,
    members_count BIGINT,
    favorites_count BIGINT,
    has_agent TINYINT(1) NOT NULL DEFAULT 0,
    bayesian_rating DECIMAL(4,2),
    mean_rating DECIMAL(4,2),
    rating_count BIGINT,
    community_bayesian_rating DECIMAL(4,2),
    community_mean_rating DECIMAL(4,2),
    community_rating_count BIGINT NOT NULL DEFAULT 0,
    firefly_vote_count BIGINT NOT NULL DEFAULT 0,
    studio VARCHAR(100),
    source VARCHAR(50),
    season VARCHAR(20),
    year INT,
    created_at DATETIME(6),
    updated_at DATETIME(6),
    synced_at DATETIME(6),
    PRIMARY KEY (id),
    UNIQUE KEY idx_mal_id (mal_id),
    KEY idx_rating (bayesian_rating DESC),
    KEY idx_popularity (popularity),
    KEY idx_has_agent (has_agent),
    KEY idx_title_cn (title_cn),
    KEY idx_community_rating (community_bayesian_rating DESC),
    KEY idx_firefly_votes (firefly_vote_count DESC),
    KEY idx_anime_year_season (year, season),
    KEY idx_anime_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS anime_genres (
    anime_id BIGINT NOT NULL,
    genre VARCHAR(255),
    KEY idx_anime_genres_anime (anime_id),
    CONSTRAINT fk_anime_genres_anime FOREIGN KEY (anime_id) REFERENCES anime (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_characters (
    id BIGINT NOT NULL AUTO_INCREMENT,
    code VARCHAR(50) NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    source_title VARCHAR(120),
    avatar_url VARCHAR(500),
    background_url VARCHAR(500),
    personality VARCHAR(1000),
    speech_style VARCHAR(1000),
    catchphrases VARCHAR(500),
    extra_prompt TEXT,
    prompt_template TEXT,
    voice_id VARCHAR(120),
    opening_audio_url VARCHAR(500),
    model VARCHAR(120),
    temperature DOUBLE,
    max_tokens INT,
    enabled BIT(1),
    sort_order INT,
    created_at DATETIME(6),
    updated_at DATETIME(6),
    PRIMARY KEY (id),
    UNIQUE KEY idx_agent_character_code (code),
    KEY idx_agent_character_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_vote_candidates (
    id BIGINT NOT NULL AUTO_INCREMENT,
    code VARCHAR(50) NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    source_title VARCHAR(120),
    avatar_url VARCHAR(500),
    personality VARCHAR(1000),
    speech_style VARCHAR(1000),
    catchphrases VARCHAR(500),
    extra_prompt TEXT,
    vote_count BIGINT DEFAULT 0,
    is_winner TINYINT(1) DEFAULT 0,
    week_key VARCHAR(10),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_agent_candidate_week (code, week_key),
    KEY idx_candidate_week (week_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_votes (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    candidate_id BIGINT NOT NULL,
    week_key VARCHAR(10),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_week (user_id, week_key),
    KEY idx_agent_vote_candidate (candidate_id),
    CONSTRAINT fk_agent_vote_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_agent_vote_candidate FOREIGN KEY (candidate_id) REFERENCES agent_vote_candidates (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ratings (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    anime_id BIGINT NOT NULL,
    score DECIMAL(3,1) NOT NULL,
    review VARCHAR(1000),
    story_score DECIMAL(3,1),
    animation_score DECIMAL(3,1),
    sound_score DECIMAL(3,1),
    character_score DECIMAL(3,1),
    enjoyment_score DECIMAL(3,1),
    is_recommended BIT(1),
    contains_spoiler BIT(1),
    like_count BIGINT,
    created_at DATETIME(6),
    updated_at DATETIME(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_anime_rating (user_id, anime_id),
    KEY idx_anime_rating (anime_id, score DESC),
    KEY idx_user_rating (user_id, created_at DESC),
    KEY idx_created_at (created_at),
    CONSTRAINT fk_ratings_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_ratings_anime FOREIGN KEY (anime_id) REFERENCES anime (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rating_replies (
    id BIGINT NOT NULL AUTO_INCREMENT,
    rating_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content VARCHAR(800) NOT NULL,
    like_count BIGINT,
    created_at DATETIME(6),
    updated_at DATETIME(6),
    PRIMARY KEY (id),
    KEY idx_rating_reply (rating_id, created_at),
    KEY idx_reply_user (user_id, created_at),
    CONSTRAINT fk_rating_replies_rating FOREIGN KEY (rating_id) REFERENCES ratings (id),
    CONSTRAINT fk_rating_replies_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS communities (
    id BIGINT NOT NULL AUTO_INCREMENT,
    slug VARCHAR(80) NOT NULL,
    name VARCHAR(80) NOT NULL,
    description VARCHAR(500),
    cover_image VARCHAR(500),
    category VARCHAR(50),
    tags VARCHAR(500),
    related_anime_id BIGINT,
    post_count BIGINT NOT NULL,
    member_count BIGINT NOT NULL,
    heat_score BIGINT NOT NULL,
    is_featured BIT(1) NOT NULL,
    creator_id BIGINT,
    created_at DATETIME(6),
    updated_at DATETIME(6),
    PRIMARY KEY (id),
    UNIQUE KEY idx_community_slug (slug),
    KEY idx_community_category (category),
    KEY idx_community_heat (heat_score DESC),
    KEY idx_community_anime (related_anime_id),
    CONSTRAINT fk_community_anime FOREIGN KEY (related_anime_id) REFERENCES anime (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS community_posts (
    id BIGINT NOT NULL AUTO_INCREMENT,
    community_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL,
    content TEXT NOT NULL,
    cover_image VARCHAR(500),
    images TEXT,
    like_count BIGINT NOT NULL,
    reply_count BIGINT NOT NULL,
    view_count BIGINT NOT NULL,
    is_pinned BIT(1) NOT NULL,
    is_featured BIT(1) NOT NULL,
    is_deleted BIT(1) NOT NULL,
    last_replied_at DATETIME(6),
    created_at DATETIME(6),
    updated_at DATETIME(6),
    PRIMARY KEY (id),
    KEY idx_post_community_reply (community_id, last_replied_at),
    KEY idx_post_community_created (community_id, created_at),
    KEY idx_post_author (user_id, created_at),
    CONSTRAINT fk_community_posts_community FOREIGN KEY (community_id) REFERENCES communities (id),
    CONSTRAINT fk_community_posts_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS community_replies (
    id BIGINT NOT NULL AUTO_INCREMENT,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content VARCHAR(1200) NOT NULL,
    like_count BIGINT NOT NULL,
    is_deleted BIT(1) NOT NULL,
    created_at DATETIME(6),
    updated_at DATETIME(6),
    PRIMARY KEY (id),
    KEY idx_community_reply_post (post_id, created_at),
    KEY idx_community_reply_user (user_id, created_at),
    CONSTRAINT fk_community_replies_post FOREIGN KEY (post_id) REFERENCES community_posts (id),
    CONSTRAINT fk_community_replies_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS firefly_votes (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    anime_id BIGINT NOT NULL,
    created_at DATETIME(6),
    PRIMARY KEY (id),
    KEY idx_firefly_vote_anime (anime_id, created_at),
    KEY idx_firefly_vote_user (user_id, created_at),
    CONSTRAINT fk_firefly_votes_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_firefly_votes_anime FOREIGN KEY (anime_id) REFERENCES anime (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
